### ISSUE TITLE
Repo topics to review

### ISSUE THREAD

**Issue by maelle** [mpadge/osmplotr#40]
:wave: @mpadge I've added repo topics to increase discoverability, please review&tweak the list 😸 

![image](https://user-images.githubusercontent.com/8360597/40099570-e3f139aa-58e0-11e8-9acd-30a660509887.png)

**Comment by mpadge** [comment]
Thanks Maelle! See you next week!

**Comment by maelle** [comment]
Thank _you_ and see you soon!
