### ISSUE TITLE
Salvage performant/useful code from the overpass package

### ISSUE THREAD

**Issue by Robinlovelace** [mpadge/osmplotr#5]
As part of a 'package race' with @timeportfolio and someone else, and partly instigated by me, the prolific @hrbrmstr created the overpass package: https://github.com/hrbrmstr/overpass

Serendipitously I met up with Bob at the #runconference and he gives us permission to 'pillage' his code for this. I suggest we do precisely that but use the more amicable term 'salvage' and give him full credit for the functions he created. No details here but if you check out the innards of those functions in overpass, there's some clever stuff going on - it even gives you a progress bar for some operations which is awesome!

Not sure if this is an issue for here your/our new project https://github.com/osmdatar/osmdatar but certain it's an issue worth raising that will lead to good things.

**Comment by mpadge** [comment]
discussion shifted to [osmdatar](https://github.com/osmdatar/osmdatar)
