### ISSUE TITLE
upgrade to new spatstat packages

### ISSUE THREAD

**Issue by mpadge** [mpadge/osmplotr#55]
Wait until mid-Jan or so, and modify as generated in revdep files [here](https://github.com/rubak/spatstat.revdep/tree/main/osmplotr)

**Comment by rjwest000** [comment]
Hi there:
I am receiving an error (see below) when loading the package on either my linux or Mac computers. 
 - osmplotr is ver 0.3-2
 - spatstat is ver 2.3-4
Are these incompatible? Any solution? Thanks.

  > library (osmplotr)
     Error: package or namespace load failed for ‘osmplotr’:
     object ‘Smooth’ is not exported by 'namespace:spatstat'_

**Comment by maelle** [comment]
@mpadge didn't you do this?

**Comment by mpadge** [comment]
Yep, sure did; thanks!
