### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [mpadge/osmplotr#56]
We get

```r
 Error : In '_pkgdown.yml', topic must be a known selector function
✖ Not 'osmplotr-package'
```

I think the easiest fix is to add

```r
#' @keywords internal
```

for that topic then redocumenting.

**Comment by maelle** [comment]
@mpadge friendly reminder :smile_cat:

**Comment by mpadge** [comment]
sorry @maelle, i still can't run `check_pkgdown()` locally, so it's a bit more effort for me to run those checks. Anyway, i checked the above in a container, and all was good. Thanks

**Comment by maelle** [comment]
Thank you!!
