### ISSUE TITLE
Action needed before 2023-01-25: update osmplotr's dependencies as it cannot be built

### ISSUE THREAD

**Issue by maelle** [mpadge/osmplotr#60]
:wave: @mpadge!

Your osmplotr package cannot be built on R-universe as it depends on the deprecated spatial package rgeos. See for instance this [write up by Jakub Nowosad to understand the changes in the R spatial ecosystem](https://geocompx.org/post/2023/rgdal-retirement/index.html). :world_map: 

**Please indicate us before January, the 25th whether you intend to update your package.** If not, we will archive osmplotr* and remove it from rOpenSci registry. You do not need to make changes before January, the 25th; but you do need to drop us a line before then.

You can find [help](https://devdevguide.netlify.app/maintenance_cheatsheet), among other places, in our Slack's workspace "spatial" and "package-maintenance" channels.

Thank you! :pray:

*: We can unarchive the repository and transfer it to your own account, at your request. We won't shred it. :smile_cat: 

@ropensci/admin

**Comment by maelle** [comment]
Reminder sent per email.

**Comment by mpadge** [comment]
Thanks, and yes, i intend to update this package before that date. I'll let you know here when that's been done

**Comment by mpadge** [comment]
rgeos dep removed :+1:

**Comment by maelle** [comment]
:tada: Thank you!

**Comment by mpadge** [comment]
Thanks for pushing that - been meaning to do that for (obviously ...) a long time
