### ISSUE TITLE
use git tags, and releases

### ISSUE THREAD

**Issue by sckott** [mpadge/osmplotr#8]
hey @mpadge  - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  
- You already use a `NEWS` file, thanks!
- Please do `git tag` each version that's pushed to CRAN
- use the [releases tab](https://github.com/ropenscilabs/osmplotr/releases) on this repo to include the associated NEWS items for each tag/version

Can you please do the two above items from now on?

**Comment by mpadge** [comment]
Thanks @sckott , all releases now tagged and described as requested.

**Comment by sckott** [comment]
thanks
