### ISSUE TITLE
git repo title

### ISSUE THREAD

**Issue by mpadge** [mpadge/osmplotr#9]
@sckott , could you please edit the title of my git repo to reflect text in DESCRIPTION?
(It would of course be good for repo owner to be able to do this themselves, but I guess that'd be nigh on impossible without allowing that ability for all ropensci repos, which'd obviously be unwise.) Thanks!

**Comment by sckott** [comment]
sure thing, you want this?

> Customisable images of OpenStreetMap (OSM) data and data visualisation using OSM objects

**Comment by mpadge** [comment]
Yup @sckott , that'd be grand.

**Comment by sckott** [comment]
done
